Support/wagtail 50
wagtail/wagtail-factories pull request #80
Opened 2023-10-06 12:51 UTC by lparsons396

- Update testing matrix to include Wagtail 5.1
- Drop support for Python 3.7

2023-10-06 13:35 UTC, zerolab requested changes

2023-10-06 13:35 UTC, zerolab commented on CHANGES
> +- Drop support for Django 3.7
https://github.com/wagtail/wagtail-factories/blob/main/setup.py#L57 needs removing

2023-10-06 13:35 UTC, zerolab commented on tox.ini
> +    py{38,39,310}-django{32,41}-wagtail{41,42,50,51}-factoryboy32
```suggestion
    py{38,39,310}-django{32,41}-wagtail{41,50,51}-factoryboy32
```

2023-10-06 13:35 UTC, zerolab commented on tox.ini
> +    py311-django41-wagtail{41,42,50,51}-factoryboy32
```suggestion
    py311-django41-wagtail{41,50,51}-factoryboy32
```

2023-10-06 13:35 UTC, zerolab commented on tox.ini
> +    py311-django41-wagtail{41,42,50,51}-factoryboy32
and the `wagtail42: wagtail>=4.2,<5.0` line can go

2023-11-17 08:16 UTC, katdom13 commented
Superseded by: https://github.com/wagtail/wagtail-factories/pull/81

2024-02-17 16:31 UTC, closed without merging